# this is just a config file for gitpod. See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

tasks:
  - name: Run Hello World Worker
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v" # can't run tctl directly from gitpod.yml
      cd hello-world
      npm install
    command: |
      gp open .gitpod.readme.md
      gp sync-await server-up
      npm run start.watch
  - name: Run Hello World Workflow
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v" # can't run tctl directly from gitpod.yml
    command: |
      cd hello-world # gitpod prebuild doesnt persist the cd
      until npm run workflow; do clear; sleep 5; done; # "sleep until temporal is actually up"
      gp sync-done server-up
      gp preview http://localhost:8088 # open up Temporal Web to show new workflow
      npm run workflow # run workflow again for user's easy access
    openMode: split-right
  - name: Temporal Server
    init: docker-compose pull
    command: docker-compose up

ports:
  - port: 5432 #postgres
    onOpen: ignore
  - port: 7233 #temporal server
    onOpen: ignore
  - port: 8088 #temporal web
    onOpen: ignore
    visibility: public

# notes for future temporalite usage
#  - name: Temporalite
#    init: go install github.com/DataDog/temporalite/cmd/temporalite@latest
#    command: temporalite start --namespace default -f my-test.db
# separate temporal web
#      docker run -t -i -p 8088:8088 -e TEMPORAL_GRPC_ENDPOINT=temporal:7233 temporalio/web:1.12.0 # this does not work yet :(
