# Technically speaking, this repo is not really meant to be a monorepo. That is, each directory is
# really a separate workspace, with no dependency between them, and each directory is meant to be
# used as a template for a new project, completely unrelated from the rest of this repository.
# But loading them all as a single workspace makes it easier to execute commands across packages,
# and gives an incredible speed boost when running `pnpm install` or `pnpm update`.
packages:
  - '*'
  - 'message-passing/*'
  - 'monorepo-folders/packages/*'
  - 'food-delivery/apps/*'
  - 'food-delivery/packages/*'
  - 'openai-agents/*'
  - 'polling/*'

linkWorkspacePackages: true
sharedWorkspaceLockfile: true
hoist: false

# By default, PNPM hoists eslint and prettier to the workspace root, but that may causes issues
# with this workspace, as some samples have completely different versions of these packages, or
# depends on incompatible plugins.
#
# The monorepo sample uses postcss with an external configuration file that refers to plugins by
# their package name, rather than passing objects. That doesn't work with PNPM's strict node_modules
# structure. To work around this, hoist all postcss-* packages.
# FIXME: Can't we do something equivalent at the project-level instead?
publicHoistPattern:
  - postcss-*

allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  deasync: true
  esbuild: true
  protobufjs: true
  sharp: true
  vercel: true
