#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# npx lint-staged

for file in *; do
  if [[ -d "$file" ]] # is a directory?
  then
    if ! [[ " node_modules ecommerce-one-click " =~ " $file " ]]
    then
      cp .shared/tsconfig.json $file/
      git add $file/tsconfig.json

      cp .shared/.gitignore $file/
      git add $file/.gitignore

      cp .shared/.npmrc $file/
      git add $file/.npmrc

      cp .shared/.nvmrc $file/
      git add $file/.nvmrc
    fi
  fi
done